import React from 'react';
import ITreeNavOption from '../../types/TreeNavOption';
import ITreeNavRoot from '../../types/TreeNavRoot';
import './TreeNavigation.css';
import TreeNavOption from '../TreeNavOption';

const TreeNavigation: React.FC = () => {

    // IDEALLY, THIS TREE NAVIGATION WOULD BE GENERATED BY JSON DATA, STRUCTURED EXACTLY AS ITS DISPLAYED IN THE UI...
    // I.E. PARENT ELEMENTS WITH ARRAYS OF CHILDREN. I DON'T PARTICULARLY LIKE THE IMPLEMENTATION I'VE COME UP WITH
    // BELOW AND I WOULD CHANGE IT I CREATED A JSON API TO PASS ME THE DATA IN THE FORMAT DESCRIBED  :)

    const treeNavOption_0:      ITreeNavOption = { id: '0',      name: 'all',                        hasChildren: false };

    const treeNavOption_1:      ITreeNavOption = { id: '1',      name: 'Business Capability 1',      hasChildren: true };
    const treeNavOption_1_1:    ITreeNavOption = { id: '1.1',    name: 'Business Capability 1.1',    hasChildren: true };
    const treeNavOption_1_1_1:  ITreeNavOption = { id: '1.1.1',  name: 'Business Capability 1.1.1',  hasChildren: false };
    const treeNavOption_1_1_2:  ITreeNavOption = { id: '1.1.2',  name: 'Business Capability 1.1.2',  hasChildren: false };
    const treeNavOption_1_1_3:  ITreeNavOption = { id: '1.1.3',  name: 'Business Capability 1.1.3',  hasChildren: false };
    const treeNavOption_1_2:    ITreeNavOption = { id: '1.2',    name: 'Business Capability 1.2',    hasChildren: true };
    const treeNavOption_1_2_1:  ITreeNavOption = { id: '1.2.1',  name: 'Business Capability 1.2.1',  hasChildren: false };
    const treeNavOption_1_2_2:  ITreeNavOption = { id: '1.2.2',  name: 'Business Capability 1.2.2',  hasChildren: false };
    const treeNavOption_1_2_3:  ITreeNavOption = { id: '1.2.3',  name: 'Business Capability 1.2.3',  hasChildren: false };
    const treeNavOption_1_3:    ITreeNavOption = { id: '1.3',    name: 'Business Capability 1.3',    hasChildren: true };
    const treeNavOption_1_3_1:  ITreeNavOption = { id: '1.3.1',  name: 'Business Capability 1.3.1',  hasChildren: false };
    const treeNavOption_1_3_2:  ITreeNavOption = { id: '1.3.2',  name: 'Business Capability 1.3.2',  hasChildren: false };
    const treeNavOption_1_3_3:  ITreeNavOption = { id: '1.3.3',  name: 'Business Capability 1.3.3',  hasChildren: false };

    const treeNavOption_2:      ITreeNavOption = { id: '2',      name: 'Business Capability 2',      hasChildren: true };
    const treeNavOption_2_1:    ITreeNavOption = { id: '2.1',    name: 'Business Capability 2.1',    hasChildren: true };
    const treeNavOption_2_1_1:  ITreeNavOption = { id: '2.1.1',  name: 'Business Capability 2.1.1',  hasChildren: false };
    const treeNavOption_2_1_2:  ITreeNavOption = { id: '2.1.2',  name: 'Business Capability 2.1.2',  hasChildren: false };
    const treeNavOption_2_1_3:  ITreeNavOption = { id: '2.1.3',  name: 'Business Capability 2.1.3',  hasChildren: false };
    const treeNavOption_2_2:    ITreeNavOption = { id: '2.2',    name: 'Business Capability 2.2',    hasChildren: true };
    const treeNavOption_2_2_1:  ITreeNavOption = { id: '2.2.1',  name: 'Business Capability 2.2.1',  hasChildren: false };
    const treeNavOption_2_2_2:  ITreeNavOption = { id: '2.2.2',  name: 'Business Capability 2.2.2',  hasChildren: false };
    const treeNavOption_2_2_3:  ITreeNavOption = { id: '2.2.3',  name: 'Business Capability 2.2.3',  hasChildren: false };
    const treeNavOption_2_3:    ITreeNavOption = { id: '2.3',    name: 'Business Capability 2.3',    hasChildren: true };
    const treeNavOption_2_3_1:  ITreeNavOption = { id: '2.3.1',  name: 'Business Capability 2.3.1',  hasChildren: false };
    const treeNavOption_2_3_2:  ITreeNavOption = { id: '2.3.2',  name: 'Business Capability 2.3.2',  hasChildren: false };
    const treeNavOption_2_3_3:  ITreeNavOption = { id: '2.3.3',  name: 'Business Capability 2.3.3',  hasChildren: false };

    const treeNavOption_3:      ITreeNavOption = { id: '3',      name: 'Business Capability 3',      hasChildren: true };
    const treeNavOption_3_1:    ITreeNavOption = { id: '3.1',    name: 'Business Capability 3.1',    hasChildren: true };
    const treeNavOption_3_1_1:  ITreeNavOption = { id: '3.1.1',  name: 'Business Capability 3.1.1',  hasChildren: false };
    const treeNavOption_3_1_2:  ITreeNavOption = { id: '3.1.2',  name: 'Business Capability 3.1.2',  hasChildren: false };
    const treeNavOption_3_1_3:  ITreeNavOption = { id: '3.1.3',  name: 'Business Capability 3.1.3',  hasChildren: false };
    const treeNavOption_3_2:    ITreeNavOption = { id: '3.2',    name: 'Business Capability 3.2',    hasChildren: true };
    const treeNavOption_3_2_1:  ITreeNavOption = { id: '3.2.1',  name: 'Business Capability 3.2.1',  hasChildren: false };
    const treeNavOption_3_2_2:  ITreeNavOption = { id: '3.2.2',  name: 'Business Capability 3.2.2',  hasChildren: false };
    const treeNavOption_3_2_3:  ITreeNavOption = { id: '3.2.3',  name: 'Business Capability 3.2.3',  hasChildren: false };
    const treeNavOption_3_3:    ITreeNavOption = { id: '3.3',    name: 'Business Capability 3.3',    hasChildren: true };
    const treeNavOption_3_3_1:  ITreeNavOption = { id: '3.3.1',  name: 'Business Capability 3.3.1',  hasChildren: false };
    const treeNavOption_3_3_2:  ITreeNavOption = { id: '3.3.2',  name: 'Business Capability 3.3.2',  hasChildren: false };
    const treeNavOption_3_3_3:  ITreeNavOption = { id: '3.3.3',  name: 'Business Capability 3.3.3',  hasChildren: false };

    const treeNavRoot_0:            ITreeNavRoot = { level: 1, options: [treeNavOption_0] };

    const treeNavRoot_1:            ITreeNavRoot = { level: 1, options: [treeNavOption_1] };
    const treeNavRoot_1_1:          ITreeNavRoot = { level: 2, options: [treeNavOption_1_1] };
    const treeNavRoot_1_1_children: ITreeNavRoot = { level: 3, options: [treeNavOption_1_1_1, treeNavOption_1_1_2, treeNavOption_1_1_3] };
    const treeNavRoot_1_2:          ITreeNavRoot = { level: 2, options: [treeNavOption_1_2] };
    const treeNavRoot_1_2_children: ITreeNavRoot = { level: 3, options: [treeNavOption_1_2_1, treeNavOption_1_2_2, treeNavOption_1_2_3] };
    const treeNavRoot_1_3:          ITreeNavRoot = { level: 2, options: [treeNavOption_1_3] };
    const treeNavRoot_1_3_children: ITreeNavRoot = { level: 3, options: [treeNavOption_1_3_1, treeNavOption_1_3_2, treeNavOption_1_3_3] };

    const treeNavRoot_2:            ITreeNavRoot = { level: 1, options: [treeNavOption_2] };
    const treeNavRoot_2_1:          ITreeNavRoot = { level: 2, options: [treeNavOption_2_1] };
    const treeNavRoot_2_1_children: ITreeNavRoot = { level: 3, options: [treeNavOption_2_1_1, treeNavOption_2_1_2, treeNavOption_2_1_3] };
    const treeNavRoot_2_2:          ITreeNavRoot = { level: 2, options: [treeNavOption_2_2] };
    const treeNavRoot_2_2_children: ITreeNavRoot = { level: 3, options: [treeNavOption_2_2_1, treeNavOption_2_2_2, treeNavOption_2_2_3] };
    const treeNavRoot_2_3:          ITreeNavRoot = { level: 2, options: [treeNavOption_2_3] };
    const treeNavRoot_2_3_children: ITreeNavRoot = { level: 3, options: [treeNavOption_2_3_1, treeNavOption_2_3_2, treeNavOption_2_3_3] };

    const treeNavRoot_3:            ITreeNavRoot = { level: 1, options: [treeNavOption_3] };
    const treeNavRoot_3_1:          ITreeNavRoot = { level: 2, options: [treeNavOption_3_1] };
    const treeNavRoot_3_1_children: ITreeNavRoot = { level: 3, options: [treeNavOption_3_1_1, treeNavOption_3_1_2, treeNavOption_3_1_3] };
    const treeNavRoot_3_2:          ITreeNavRoot = { level: 2, options: [treeNavOption_3_2] };
    const treeNavRoot_3_2_children: ITreeNavRoot = { level: 3, options: [treeNavOption_3_2_1, treeNavOption_3_2_2, treeNavOption_3_2_3] };
    const treeNavRoot_3_3:          ITreeNavRoot = { level: 2, options: [treeNavOption_3_3] };
    const treeNavRoot_3_3_children: ITreeNavRoot = { level: 3, options: [treeNavOption_3_3_1, treeNavOption_3_3_2, treeNavOption_3_3_3] };

    const renderTreeNavRootAndOptions = (treeNavRoot: ITreeNavRoot): JSX.Element => {
        const treeRootId: string = (treeNavRoot.options[0].id.length === 5) ? treeNavRoot.options[0].id.substring(0, 3) + '_children' : treeNavRoot.options[0].id;
        return (
            <ul data-level={treeNavRoot.level} data-root-id={treeRootId} data-visibility={(treeNavRoot.level === 1) ? 'visible' : 'hidden'}>
                {treeNavRoot.options.map(treeNavOption => (
                    <TreeNavOption key={treeNavOption.id} id={treeNavOption.id} name={treeNavOption.name} hasChildren={treeNavOption.hasChildren} />
                ))}
            </ul>
        )
    }

    return (
        <nav id="treeNavigation">
            {renderTreeNavRootAndOptions(treeNavRoot_0)}
            {renderTreeNavRootAndOptions(treeNavRoot_1)}
            {renderTreeNavRootAndOptions(treeNavRoot_1_1)}
            {renderTreeNavRootAndOptions(treeNavRoot_1_1_children)}
            {renderTreeNavRootAndOptions(treeNavRoot_1_2)}
            {renderTreeNavRootAndOptions(treeNavRoot_1_2_children)}
            {renderTreeNavRootAndOptions(treeNavRoot_1_3)}
            {renderTreeNavRootAndOptions(treeNavRoot_1_3_children)}
            {renderTreeNavRootAndOptions(treeNavRoot_2)}
            {renderTreeNavRootAndOptions(treeNavRoot_2_1)}
            {renderTreeNavRootAndOptions(treeNavRoot_2_1_children)}
            {renderTreeNavRootAndOptions(treeNavRoot_2_2)}
            {renderTreeNavRootAndOptions(treeNavRoot_2_2_children)}
            {renderTreeNavRootAndOptions(treeNavRoot_2_3)}
            {renderTreeNavRootAndOptions(treeNavRoot_2_3_children)}
            {renderTreeNavRootAndOptions(treeNavRoot_3)}
            {renderTreeNavRootAndOptions(treeNavRoot_3_1)}
            {renderTreeNavRootAndOptions(treeNavRoot_3_1_children)}
            {renderTreeNavRootAndOptions(treeNavRoot_3_2)}
            {renderTreeNavRootAndOptions(treeNavRoot_3_2_children)}
            {renderTreeNavRootAndOptions(treeNavRoot_3_3)}
            {renderTreeNavRootAndOptions(treeNavRoot_3_3_children)}
        </nav>
    )

};

export default TreeNavigation;